---
# This playbook deploys the whole application stack in this site.

- name: Installing Docker on Server
  hosts: "{{ hosts | default('all') }}"
  remote_user: '{{ remote_user }}'

  roles:
    - docker
